# fly.toml file generated for newboar on 2023-04-17T00:17:09-03:00

app = "newboar"
primary_region = "gru"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
